import os
import json
from models.pipeline_state import PipelineState
from config import GROQ_API_KEYS
from tools.llm_router import invoke_llm
from tools.prompt_cache import PR_AUTHOR_SYSTEM
from tools.confidence_calc import calculate_pipeline_confidence


async def agent_pr_author(state: PipelineState):
    GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "")
    repo_url = state.get("repo_url", "")
    repair_plan = state.get("repair_plan", [])
    security_verified = state.get("security_verified", False)

    if state.get("approval_decision") == "rejected":
        return {
            "pr_url": "",
            "confidence_score": _calculate_confidence(state, security_verified),
            "pr_error": "Repair plan was rejected by a human reviewer.",
        }

    if not GROQ_API_KEYS:
        return {
            "pr_url": "",
            "confidence_score": 0.0,
            "pr_error": "No GROQ_API_KEY set.",
        }

    patches = state.get("patches", [])
    if not patches:
        existing_error = state.get("pr_error")
        error_msg = (
            existing_error
            if existing_error
            else "No bugs were found or no patches were generated, so no PR is needed."
        )
        return {
            "pr_url": "",
            "confidence_score": _calculate_confidence(state, security_verified),
            "pr_error": error_msg,
        }

    # Tier 1 — PR title/description is simple text generation, not reasoning.
    prompt = f"""{PR_AUTHOR_SYSTEM}

Write a professional GitHub Pull Request title and description for these applied fixes:
{json.dumps(repair_plan)}
Return JSON: {{"title": "...", "description": "..."}}"""

    try:
        pr_data = await invoke_llm(
            prompt,
            agent_name="pr_author",
            tier=1,
            expect_json=True,
        )
        if pr_data.get("error"):
            pr_data = {
                "title": "Automated Security Fixes",
                "description": "Fixed vulnerabilities.",
            }
    except Exception as e:
        print(f"Error calling LLM for PR details: {e}")
        pr_data = {
            "title": "Automated Security Fixes",
            "description": "Fixed vulnerabilities.",
        }

    pr_url = ""
    pr_error = ""

    if GITHUB_TOKEN and "github.com" in repo_url:
        try:
            from tools.github_client import (
                prepare_repo_for_push,
                commit_and_push,
                open_pull_request,
            )

            repo_local_path = state.get("repo_local_path", "")
            if not repo_local_path or not os.path.exists(repo_local_path):
                pr_error = "No local repo path found to commit changes from."
                return {
                    "pr_url": "",
                    "confidence_score": _calculate_confidence(state, security_verified),
                    "pr_error": pr_error,
                }

            # 1. Prepare fork and branch
            github_data = prepare_repo_for_push(repo_url, repo_local_path, GITHUB_TOKEN)

            # 2. Add modified files
            files_to_commit = []
            for patch in patches:
                if patch.get("applied") and patch.get("file"):
                    files_to_commit.append(patch["file"])

            # 3. Commit and push
            title = pr_data.get("title", "Automated Security Fixes")

            validation_results = state.get("validation_results", [])
            validation_failed = False
            if validation_results and not validation_results[-1].get("passed", True):
                validation_failed = True
            if state.get("unresolvable_fixes"):
                validation_failed = True

            if validation_failed:
                title = f"[NEEDS WORK] {title}"

            has_changes = commit_and_push(
                local_path=repo_local_path,
                branch_name=github_data["branch_name"],
                message=title,
                push_repo_url=github_data["push_repo_url"],
                token=GITHUB_TOKEN,
                files=files_to_commit,
            )

            if not has_changes:
                pr_error = "No bugs were detected, or no valid code changes were generated by the AI."
                return {
                    "pr_url": "",
                    "confidence_score": _calculate_confidence(state, security_verified),
                    "pr_error": pr_error,
                }

            # 4. Open PR
            desc = pr_data.get("description", "Fixed vulnerabilities.")
            if isinstance(desc, list):
                desc = "- " + "\n- ".join(desc) if desc else "Fixed vulnerabilities."
            elif not isinstance(desc, str):
                desc = str(desc)

            if validation_failed:
                desc = (
                    "### ⚠️ Automated Validation Failed\nThe unit tests or syntax verification did not pass after maximum retries. This PR is submitted for manual developer review and remediation.\n\n"
                    + desc
                )

            if state.get("security_retry_context"):
                unresolved = state.get("security_retry_context", [])
                desc += "\n\n### ⚠️ Unresolved Security Risks\nThe following security issues could not be automatically verified/repaired after 3 retries:\n"
                for u in unresolved:
                    desc += f"- **{u.get('severity', 'Risk')}**: {u.get('description', str(u))}\n"

            desc += "\n\n### 📦 Modified Files\n"
            for patch in patches:
                if patch.get("applied") and patch.get("file"):
                    desc += f"- `{patch['file']}`\n"

            pr_url = open_pull_request(
                repo_name=github_data["repo_name"],
                branch_name=github_data["branch_name"],
                title=title,
                body=desc,
                token=GITHUB_TOKEN,
                is_owner=github_data["is_owner"],
                user_login=github_data["user_login"],
            )
        except Exception as e:
            import traceback

            traceback.print_exc()
            pr_error = str(e)
            print(f"GitHub API Error: {e}")
    else:
        if not GITHUB_TOKEN:
            pr_error = "GITHUB_TOKEN not set in .env"
        else:
            pr_error = "Not a GitHub URL"

    # Dynamic confidence score based on pipeline results
    confidence_score = _calculate_confidence(state, security_verified)

    result = {"pr_url": pr_url, "confidence_score": confidence_score}
    if pr_error:
        result["pr_error"] = pr_error
    return result


def _calculate_confidence(state, security_verified):
    """
    Calculate unified dynamic confidence score (0-100).
    """
    existing_chroma = state.get("confidence_score", 0.0)
    return calculate_pipeline_confidence(
        state, security_clean=security_verified, chroma_score=existing_chroma
    )
