import os
import json
from models.pipeline_state import PipelineState
from config import GROQ_API_KEYS
from tools.llm_router import invoke_llm
from tools.prompt_cache import PR_AUTHOR_SYSTEM

async def agent_pr_author(state: PipelineState):
    GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "")
    repo_url = state.get("repo_url", "")
    repair_plan = state.get("repair_plan", [])
    security_verified = state.get("security_verified", False)
    
    if not GROQ_API_KEYS:
        return {"pr_url": "", "confidence_score": 95.0, "pr_error": "No GROQ_API_KEY set."}

    patches = state.get("patches", [])
    if not patches:
        existing_error = state.get("pr_error")
        error_msg = existing_error if existing_error else "No bugs were found or no patches were generated, so no PR is needed."
        return {"pr_url": "", "confidence_score": _calculate_confidence(state, security_verified), "pr_error": error_msg}

    # Tier 1 — PR title/description is simple text generation, not reasoning.
    prompt = f"""{PR_AUTHOR_SYSTEM}

Write a professional GitHub Pull Request title and description for these applied fixes:
{json.dumps(repair_plan)}
Return JSON: {{"title": "...", "description": "..."}}"""
    
    try:
        pr_data = await invoke_llm(
            prompt,
            agent_name="pr_author",
            tier=1,
            expect_json=True,
        )
        if pr_data.get("error"):
            pr_data = {"title": "Automated Security Fixes", "description": "Fixed vulnerabilities."}
    except Exception as e:
        print(f"Error calling LLM for PR details: {e}")
        pr_data = {"title": "Automated Security Fixes", "description": "Fixed vulnerabilities."}
        
    pr_url = ""
    pr_error = ""
    
    if GITHUB_TOKEN and "github.com" in repo_url:
        try:
            from tools.github_client import prepare_repo_for_push, commit_and_push, open_pull_request
            
            repo_local_path = state.get("repo_local_path", "")
            if not repo_local_path or not os.path.exists(repo_local_path):
                pr_error = "No local repo path found to commit changes from."
                return {"pr_url": "", "confidence_score": _calculate_confidence(state, security_verified), "pr_error": pr_error}
            
            # 1. Prepare fork and branch
            github_data = prepare_repo_for_push(repo_url, repo_local_path, GITHUB_TOKEN)
            
            # 2. Add modified files
            files_to_commit = []
            for patch in patches:
                if patch.get("applied") and patch.get("file"):
                    files_to_commit.append(patch["file"])
                    
            # 3. Commit and push
            title = pr_data.get("title", "Automated Security Fixes")
            has_changes = commit_and_push(
                local_path=repo_local_path,
                branch_name=github_data["branch_name"],
                message=title,
                push_repo_url=github_data["push_repo_url"],
                token=GITHUB_TOKEN,
                files=files_to_commit
            )
            
            if not has_changes:
                pr_error = "No bugs were detected, or no valid code changes were generated by the AI."
                return {"pr_url": "", "confidence_score": _calculate_confidence(state, security_verified), "pr_error": pr_error}
                
            # 4. Open PR
            desc = pr_data.get("description", "Fixed vulnerabilities.")
            if isinstance(desc, list):
                desc = "- " + "\n- ".join(desc) if desc else "Fixed vulnerabilities."
            elif not isinstance(desc, str):
                desc = str(desc)
                
            pr_url = open_pull_request(
                repo_name=github_data["repo_name"],
                branch_name=github_data["branch_name"],
                title=title,
                body=desc,
                token=GITHUB_TOKEN,
                is_owner=github_data["is_owner"],
                user_login=github_data["user_login"]
            )
        except Exception as e:
            import traceback
            traceback.print_exc()
            pr_error = str(e)
            print(f"GitHub API Error: {e}")
    else:
        if not GITHUB_TOKEN:
            pr_error = "GITHUB_TOKEN not set in .env"
        else:
            pr_error = "Not a GitHub URL"
            
    # Dynamic confidence score based on pipeline results
    confidence_score = _calculate_confidence(state, security_verified)
    
    result = {
        "pr_url": pr_url,
        "confidence_score": confidence_score
    }
    if pr_error:
        result["pr_error"] = pr_error
    return result


def _calculate_confidence(state, security_verified):
    """
    Calculate a dynamic confidence score (0-100) based on:
    - How many issues were found and fixed
    - Whether patches applied successfully 
    - Whether validation passed
    - Whether security re-verification passed
    """
    score = 0.0
    
    investigated_issues = state.get("investigated_issues", [])
    repair_plan = state.get("repair_plan", [])
    patches = state.get("patches", [])
    validation_results = state.get("validation_results", [])
    
    # Base: 30 points for having a complete pipeline run
    if repair_plan:
        score += 30.0
    
    # Coverage: up to 25 points based on how many issues got patches
    if investigated_issues:
        coverage = len(patches) / max(len(investigated_issues), 1)
        score += min(coverage, 1.0) * 25.0
    
    # Validation: up to 25 points based on validation results
    if validation_results:
        latest = validation_results[-1]
        if latest.get("passed"):
            score += 25.0
        else:
            # Partial credit if some files passed
            files_passed = latest.get("files_passed", 0)
            files_total = latest.get("files_validated", 1)
            score += (files_passed / max(files_total, 1)) * 15.0
    
    # Security: 20 points if security re-verification passed
    if security_verified:
        score += 20.0
    else:
        score += 5.0  # Small credit for completing the step
    
    return round(min(score, 100.0), 1)