name: Trigger auto deployment for codesentinel-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/codesentinel-api-AutoDeployTrigger-02e6a4c1-9036-4865-be40-e07f078344ba.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo
      packages: write #Required to push to GHCR

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CODESENTINELAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CODESENTINELAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CODESENTINELAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/backend
          dockerfilePath: Dockerfile
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.CODESENTINELAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CODESENTINELAPI_REGISTRY_PASSWORD }}
          containerAppName: codesentinel-api
          resourceGroup: CodeSentinel-RG
          imageToBuild: ghcr.io/${{ github.repository_owner }}/codesentinel-backend:${{ github.sha }}
          targetPort: 8000
          environmentVariables: |
            GROQ_API_KEY=secretref:groq-api-key
            GITHUB_TOKEN=secretref:github-token
            ADMIN_SECRET=secretref:admin-secret
            PORT=8000
            CORS_ORIGINS=https://salmon-ground-0362fac00.7.azurestaticapps.net

